; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-apple-darwin < %s | FileCheck %s

define i32 @and_freeze_load_i32_to_i8(ptr %p) {
; CHECK-LABEL: and_freeze_load_i32_to_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 255
  ret i32 %masked
}

define i32 @and_freeze_load_i32_to_i16(ptr %p) {
; CHECK-LABEL: and_freeze_load_i32_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrh w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 65535
  ret i32 %masked
}

define i64 @and_freeze_load_i64_to_i8(ptr %p) {
; CHECK-LABEL: and_freeze_load_i64_to_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %masked = and i64 %freeze, 255
  ret i64 %masked
}

define i64 @and_freeze_load_i64_to_i16(ptr %p) {
; CHECK-LABEL: and_freeze_load_i64_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrh w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %masked = and i64 %freeze, 65535
  ret i64 %masked
}

define i64 @and_freeze_load_i64_to_i32(ptr %p) {
; CHECK-LABEL: and_freeze_load_i64_to_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %masked = and i64 %freeze, 4294967295
  ret i64 %masked
}

define i32 @and_freeze_load_shifted_mask(ptr %p) {
; CHECK-LABEL: and_freeze_load_shifted_mask:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w8, [x0, #1]
; CHECK-NEXT:    lsl w0, w8, #8
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 65280
  ret i32 %masked
}

define i8 @trunc_freeze_load_i16_to_i8(ptr %p) {
; CHECK-LABEL: trunc_freeze_load_i16_to_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i16, ptr %p, align 2
  %freeze = freeze i16 %load
  %trunc = trunc i16 %freeze to i8
  ret i8 %trunc
}

define i8 @trunc_freeze_load_i32_to_i8(ptr %p) {
; CHECK-LABEL: trunc_freeze_load_i32_to_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %trunc = trunc i32 %freeze to i8
  ret i8 %trunc
}

define i8 @trunc_freeze_load_i64_to_i8(ptr %p) {
; CHECK-LABEL: trunc_freeze_load_i64_to_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %trunc = trunc i64 %freeze to i8
  ret i8 %trunc
}

define i16 @trunc_freeze_load_i64_to_i16(ptr %p) {
; CHECK-LABEL: trunc_freeze_load_i64_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrh w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %trunc = trunc i64 %freeze to i16
  ret i16 %trunc
}

define i16 @trunc_freeze_load_i32_to_i16(ptr %p) {
; CHECK-LABEL: trunc_freeze_load_i32_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %trunc = trunc i32 %freeze to i16
  ret i16 %trunc
}

define i32 @sext_inreg_freeze_load_i8(ptr %p) {
; CHECK-LABEL: sext_inreg_freeze_load_i8:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrsb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %shl = shl i32 %freeze, 24
  %ashr = ashr i32 %shl, 24
  ret i32 %ashr
}

define i32 @sext_inreg_freeze_load_i16(ptr %p) {
; CHECK-LABEL: sext_inreg_freeze_load_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrsh w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %shl = shl i32 %freeze, 16
  %ashr = ashr i32 %shl, 16
  ret i32 %ashr
}

define i32 @zext_trunc_freeze_load(ptr %p) {
; CHECK-LABEL: zext_trunc_freeze_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %trunc = trunc i64 %freeze to i8
  %zext = zext i8 %trunc to i32
  ret i32 %zext
}

define i32 @sext_trunc_freeze_load(ptr %p) {
; CHECK-LABEL: sext_trunc_freeze_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrsb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %trunc = trunc i64 %freeze to i8
  %sext = sext i8 %trunc to i32
  ret i32 %sext
}

define i32 @trunc_freeze_load_store(ptr %p, ptr %q) {
; CHECK-LABEL: trunc_freeze_load_store:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w8, [x0]
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    strb w8, [x1]
; CHECK-NEXT:    ret
  %load = load i16, ptr %p, align 4
  %freeze = freeze i16 %load
  %trunc = trunc i16 %freeze to i8
  store i8 %trunc, ptr %q, align 1
  ret i32 0
}

define i32 @and_freeze_load_unaligned(ptr %p) {
; CHECK-LABEL: and_freeze_load_unaligned:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w0, [x0]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 1
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 255
  ret i32 %masked
}

define i32 @and_freeze_volatile_load(ptr %p) {
; CHECK-LABEL: and_freeze_volatile_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    and w0, w8, #0xff
; CHECK-NEXT:    ret
  %load = load volatile i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 255
  ret i32 %masked
}

define i32 @and_freeze_atomic_load(ptr %p) {
; CHECK-LABEL: and_freeze_atomic_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldar w8, [x0]
; CHECK-NEXT:    and w0, w8, #0xff
; CHECK-NEXT:    ret
  %load = load atomic i32, ptr %p seq_cst, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 255
  ret i32 %masked
}

define i32 @and_freeze_non_contiguous_mask(ptr %p) {
; CHECK-LABEL: and_freeze_non_contiguous_mask:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    mov w9, #170 ; =0xaa
; CHECK-NEXT:    and w0, w8, w9
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 170
  ret i32 %masked
}

define i32 @and_freeze_variable_mask(ptr %p, i32 %mask) {
; CHECK-LABEL: and_freeze_variable_mask:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    and w0, w8, w1
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, %mask
  ret i32 %masked
}

define i32 @and_multiuse_freeze_extload_no_narrow(ptr %p) {
; CHECK-LABEL: and_multiuse_freeze_extload_no_narrow:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldrb w8, [x0]
; CHECK-NEXT:    cmp w8, #42
; CHECK-NEXT:    csel w0, w8, wzr, eq
; CHECK-NEXT:    ret
  %load = load i8, ptr %p
  %freeze = freeze i8 %load
  %zext = zext i8 %freeze to i32
  %cmp = icmp eq i8 %freeze, 42
  %sel = select i1 %cmp, i32 %zext, i32 0
  ret i32 %sel
}

define i32 @and_multiuse_freeze_narrowing(ptr %p, ptr %q) {
; CHECK-LABEL: and_multiuse_freeze_narrowing:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    and w0, w8, #0xff
; CHECK-NEXT:    str w8, [x1]
; CHECK-NEXT:    ret
  %load = load i32, ptr %p
  %freeze = freeze i32 %load
  %masked = and i32 %freeze, 255
  store i32 %freeze, ptr %q
  ret i32 %masked
}

define i64 @and_multiuse_freeze_i64_narrowing(ptr %p, ptr %q) {
; CHECK-LABEL: and_multiuse_freeze_i64_narrowing:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr x8, [x0]
; CHECK-NEXT:    and x0, x8, #0xff
; CHECK-NEXT:    str x8, [x1]
; CHECK-NEXT:    ret
  %load = load i64, ptr %p
  %freeze = freeze i64 %load
  %masked = and i64 %freeze, 255
  store i64 %freeze, ptr %q
  ret i64 %masked
}

; SRL/SRA through freeze are not yet folded because the freeze peek-through
; happens after the SRL early-return in reduceLoadWidth.

define i32 @srl_freeze_load_i32(ptr %p) {
; CHECK-LABEL: srl_freeze_load_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    lsr w0, w8, #8
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %srl = lshr i32 %freeze, 8
  ret i32 %srl
}

define i32 @sra_freeze_load_i32(ptr %p) {
; CHECK-LABEL: sra_freeze_load_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    asr w0, w8, #8
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %sra = ashr i32 %freeze, 8
  ret i32 %sra
}

define i8 @trunc_srl_freeze_load(ptr %p) {
; CHECK-LABEL: trunc_srl_freeze_load:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr w8, [x0]
; CHECK-NEXT:    lsr w0, w8, #8
; CHECK-NEXT:    ret
  %load = load i32, ptr %p, align 4
  %freeze = freeze i32 %load
  %srl = lshr i32 %freeze, 8
  %trunc = trunc i32 %srl to i8
  ret i8 %trunc
}

define i16 @srl_freeze_load_i64_to_i16(ptr %p) {
; CHECK-LABEL: srl_freeze_load_i64_to_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    ldr x8, [x0]
; CHECK-NEXT:    lsr x0, x8, #16
; CHECK-NEXT:    ; kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret
  %load = load i64, ptr %p, align 8
  %freeze = freeze i64 %load
  %srl = lshr i64 %freeze, 16
  %trunc = trunc i64 %srl to i16
  ret i16 %trunc
}

; The narrowed load already exists. Replacing the load under the multi-use
; freeze makes CSE merge the freeze, and then the AND being combined, into
; existing nodes.
define i8 @and_freeze_multi_use_load_cse(i8 %a, i1 %cond, ptr %p, ptr %q) {
; CHECK-LABEL: and_freeze_multi_use_load_cse:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    tbz w1, #0, LBB28_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    mov w8, wzr
; CHECK-NEXT:    tbnz w8, #0, LBB28_3
; CHECK-NEXT:    b LBB28_4
; CHECK-NEXT:  LBB28_2: ; %body
; CHECK-NEXT:    sub sp, sp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    ldrb w8, [x2]
; CHECK-NEXT:    and w10, w0, #0xff
; CHECK-NEXT:    cmp w8, #0
; CHECK-NEXT:    strb w8, [sp, #15]
; CHECK-NEXT:    cset w9, ne
; CHECK-NEXT:    strb w8, [x3]
; CHECK-NEXT:    cmp w8, w9
; CHECK-NEXT:    and w8, w8, #0x1
; CHECK-NEXT:    csel x9, x2, x3, eq
; CHECK-NEXT:    ldrh w9, [x9]
; CHECK-NEXT:    cmp w9, #0
; CHECK-NEXT:    cset w0, ne
; CHECK-NEXT:    cmp w8, w10
; CHECK-NEXT:    cset w8, ne
; CHECK-NEXT:    add sp, sp, #16
; CHECK-NEXT:    tbz w8, #0, LBB28_4
; CHECK-NEXT:  LBB28_3: ; %exit1
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:  LBB28_4: ; %common.ret
; CHECK-NEXT:    ret
entry:
  %s = alloca i8, align 1
  br i1 %cond, label %join, label %body

body:
  %l1 = load i8, ptr %p, align 1
  store i8 %l1, ptr %s, align 1
  %l2 = load i8, ptr %p, align 1
  store i8 %l2, ptr %q, align 1
  %c1 = icmp ne i8 %l1, 0
  %z1 = zext i1 %c1 to i8
  %c2 = icmp eq i8 %l2, %z1
  %x = load i16, ptr %p, align 1
  %y = load i16, ptr %q, align 1
  %sel = select i1 %c2, i16 %x, i16 %y
  %c3 = icmp ne i16 %sel, 0
  %l3 = load i8, ptr %s, align 1
  %m = and i8 %l3, 1
  %c4 = icmp ne i8 %m, %a
  br label %join

join:
  %p1 = phi i1 [ false, %entry ], [ %c3, %body ]
  %p2 = phi i1 [ false, %entry ], [ %c4, %body ]
  br i1 %p2, label %exit1, label %exit2

exit1:
  %d = zext i8 %a to i32
  ret i8 0

exit2:
  %r = zext i1 %p1 to i8
  ret i8 %r
}
